### ISSUE TITLE
Dependabot bug

### ISSUE THREAD

**Issue by greysteil** [guitarrapc/SwapTasks#1]
Hey,

Just FYI, I've just seen a bug from Dependabot when trying to run on this repo. I'm fixing it right now.

🤖

**Comment by guitarrapc** [comment]
@greysteil oh, wow. Thank you so much for the mention!

**Comment by greysteil** [comment]
You're welcome! Should be fixed now. Dependabot had never seen a .NET repo with [this line](https://github.com/guitarrapc/SwapTasks/blob/master/src/SwapTasks/SwapTasks.csproj#L40) in it before, so couldn't handle it. All fixed now.

**Comment by guitarrapc** [comment]
I see it. Will keep using this awesome bot! Thank you for fixing!
